name: dt-bim
channels: [conda-forge, pytorch]
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - pyyaml
  - pytorch::pytorch
  - pytorch::cpuonly
  - pip
  - pip:
      - pulp
      - tqdm
      - matplotlib
